<?php

/**
 * Santa Cruz, Laguna - Barangay Hall Coordinates
 * 
 * Researcher-ready entries are transcribed from the supplied July 2026
 * Google Maps validation sheet. Rows not marked ready retain their clearly
 * labelled config-centroid fallback until they are validated.
 * 
 * Generated: July 07, 2026 12:13:14
 * Command: php artisan gis:extract-barangay-halls
 * 
 * IMPORTANT:
 * Coordinates marked as 'Needs manual validation' should be verified
 * with the Local Government Unit (LGU) before production deployment.
 */

return [
    [
        'barangay' => 'Alipit',
        'office_name' => 'Barangay Hall - Alipit',
        'latitude' => 14.22103,
        'longitude' => 121.4084,
        'address' => 'Alipit, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Bagumbayan',
        'office_name' => 'Barangay Hall - Bagumbayan',
        'latitude' => 14.27331,
        'longitude' => 121.3907,
        'address' => 'Bagumbayan, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Bubukal',
        'office_name' => 'Barangay Hall - Bubukal',
        'latitude' => 14.2591,
        'longitude' => 121.3982,
        'address' => 'Bubukal, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Calios',
        'office_name' => 'Barangay Hall - Calios',
        'latitude' => 14.27505,
        'longitude' => 121.4051,
        'address' => 'Calios, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Duhat',
        'office_name' => 'Barangay Hall - Duhat',
        'latitude' => 14.25349,
        'longitude' => 121.3827,
        'address' => 'Duhat, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Gatid',
        'office_name' => 'Barangay Hall - Gatid',
        'latitude' => 14.255,
        'longitude' => 121.4,
        'address' => 'Gatid, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'config centroid fallback',
        'validation_status' => 'Needs manual validation',
    ],
    [
        'barangay' => 'Jasaan',
        'office_name' => 'Barangay Hall - Jasaan',
        'latitude' => 14.22416,
        'longitude' => 121.3945,
        'address' => 'Jasaan, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Labuin',
        'office_name' => 'Barangay Hall - Labuin',
        'latitude' => 14.25909,
        'longitude' => 121.398,
        'address' => 'Labuin, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Malinao',
        'office_name' => 'Barangay Hall - Malinao',
        'latitude' => 14.32,
        'longitude' => 121.431,
        'address' => 'Malinao, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'config centroid fallback',
        'validation_status' => 'Needs manual validation',
    ],
    [
        'barangay' => 'Oogong',
        'office_name' => 'Barangay Hall - Oogong',
        'latitude' => 14.2266,
        'longitude' => 121.4004,
        'address' => 'Oogong, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Pagsawitan',
        'office_name' => 'Barangay Hall - Pagsawitan',
        'latitude' => 14.26586,
        'longitude' => 121.4266,
        'address' => 'Pagsawitan, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Palasan',
        'office_name' => 'Barangay Hall - Palasan',
        'latitude' => 14.25755,
        'longitude' => 121.419,
        'address' => 'Palasan, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Patimbao',
        'office_name' => 'Barangay Hall - Patimbao',
        'latitude' => 14.26679,
        'longitude' => 121.4196,
        'address' => 'Patimbao, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Poblacion I',
        'office_name' => 'Barangay Hall - Poblacion I',
        'latitude' => 14.28,
        'longitude' => 121.415,
        'address' => 'Poblacion I, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'config centroid fallback',
        'validation_status' => 'Needs manual validation',
    ],
    [
        'barangay' => 'Poblacion II',
        'office_name' => 'Barangay Hall - Poblacion II',
        'latitude' => 14.27987,
        'longitude' => 121.4171,
        'address' => 'Poblacion II, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Poblacion III',
        'office_name' => 'Barangay Hall - Poblacion III',
        'latitude' => 14.28254,
        'longitude' => 121.4162,
        'address' => 'Poblacion III, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Poblacion IV',
        'office_name' => 'Barangay Hall - Poblacion IV',
        'latitude' => 14.28479,
        'longitude' => 121.4156,
        'address' => 'Poblacion IV, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Poblacion V',
        'office_name' => 'Barangay Hall - Poblacion V',
        'latitude' => 14.285657,
        'longitude' => 121.412266,
        'address' => 'Poblacion V, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'San Jose',
        'office_name' => 'Barangay Hall - San Jose',
        'latitude' => 14.23744,
        'longitude' => 121.4039,
        'address' => 'San Jose, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'San Juan',
        'office_name' => 'Barangay Hall - San Juan',
        'latitude' => 14.2442,
        'longitude' => 121.4071,
        'address' => 'San Juan, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'San Pablo Norte',
        'office_name' => 'Barangay Hall - San Pablo Norte',
        'latitude' => 14.29135,
        'longitude' => 121.4132,
        'address' => 'San Pablo Norte, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'San Pablo Sur',
        'office_name' => 'Barangay Hall - San Pablo Sur',
        'latitude' => 14.225,
        'longitude' => 121.385,
        'address' => 'San Pablo Sur, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'config centroid fallback',
        'validation_status' => 'Needs manual validation',
    ],
    [
        'barangay' => 'Santisima Cruz',
        'office_name' => 'Barangay Hall - Santisima Cruz',
        'latitude' => 14.28799,
        'longitude' => 121.4112,
        'address' => 'Santisima Cruz, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Santo Angel Central',
        'office_name' => 'Barangay Hall - Santo Angel Central',
        'latitude' => 14.2857,
        'longitude' => 121.408,
        'address' => 'Santo Angel Central, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'Google Maps',
        'validation_status' => 'Verified',
        'verification_note' => 'Researcher verified',
    ],
    [
        'barangay' => 'Santo Angel Norte',
        'office_name' => 'Barangay Hall - Santo Angel Norte',
        'latitude' => 14.22,
        'longitude' => 121.383,
        'address' => 'Santo Angel Norte, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'config centroid fallback',
        'validation_status' => 'Needs manual validation',
    ],
    [
        'barangay' => 'Santo Angel Sur',
        'office_name' => 'Barangay Hall - Santo Angel Sur',
        'latitude' => 14.21,
        'longitude' => 121.377,
        'address' => 'Santo Angel Sur, Santa Cruz, Laguna',
        'osm_type' => null,
        'osm_id' => null,
        'source' => 'config centroid fallback',
        'validation_status' => 'Needs manual validation',
    ],
];
